package com.tradingbot.strategy.kiss.model;

import java.time.Instant;

/**
 * Represents an actionable signal generated by the KISS Strategy with full mathematical metadata.
 */
public record KissSignal(
        String symbol,
        KissSignalType signalType,
        double entryPrice,
        double stopLoss,
        double targetPrice,
        double riskAmount,
        double riskPct,
        boolean weeklyHaBullish,
        double ema55High,
        double ema55Low,
        double macdValue,
        double macdSignal,
        String reason,
        Instant timestamp) {}
