package com.tradingbot.strategy.rsihighway.model;

/**
 * Signal types generated by the RSI Highway Multi-Timeframe Strategy.
 */
public enum RsiHighwaySignalType {
    INITIAL_ENTRY,
    PYRAMID_TRANCHE_2,
    PYRAMID_TRANCHE_3,
    EXIT_RSI_50,
    EMERGENCY_EXIT,
    SL_BREACH_EXIT
}
